AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ImageUri:
    Type: String

Resources:
  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yaml

  ClusterStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cluster.yaml

  LoadBalancerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: elb.yaml
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VpcStack.Outputs.PublicSubnetIds

  ServiceStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: service.yaml
      Parameters:
        ImageUri: !Ref ImageUri
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt VpcStack.Outputs.PrivateSubnetIds
        SecurityGroupPrivateLink: !GetAtt VpcStack.Outputs.SecurityGroupPrivateLink
        ClusterName: !GetAtt ClusterStack.Outputs.ClusterName
        ECSTaskExecutionRole: !GetAtt ClusterStack.Outputs.ECSTaskExecutionRole
        TargetGroupArn: !GetAtt LoadBalancerStack.Outputs.TargetGroupArn
        SecurityGroupLoadBalancer: !GetAtt LoadBalancerStack.Outputs.SecurityGroupLoadBalancer
